### ISSUE TITLE
Add easy way to post urgent messages

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#32]
On the current website we sometimes post urgent messages like this:

![](http://i.fluffy.cc/JLTRrPQ1XCW2Jfrj5XQggXfKLm3wgxbf.png)

It would be nice if we could do something similar on ocfweb, preferably reading from an external file so we don't have to push the site to update it.

It should also allow overriding the "is lab open" check (which currently is based on [ocflib hours](https://github.com/ocf/ocflib/blob/master/ocflib/lab/hours.py)).

**Comment by matthew-mcallister** [comment]
So are we thinking something like the tried-and-true yaml file in ~staff?

**Comment by chriskuehl** [comment]
I think so. A YAML file of this format maybe?

```yaml
# Whether to override the default "lab is open" logic. This can be
# used to force the lab to be closed in an emergency.
#
# For regular scheduled holidays, add them to ocflib instead.
# (See `pydoc3 ocflib.lab.hours` for more details.)
#
# If override_lab_hours is true, then `lab_open` controls whether
# the lab is considered open or not.
override_lab_hours: false
lab_open: false

# Whether to display an urgent status message on the home page.
#
# The urgent message can contain HTML. The recommended format is
# an <h2> title and <p> paragraphs with more info.
display_urgent_message: false
urgent_message: |
    <h2>The lab is currently closed due to xyz</h2>
    <p>For more info, visit <a href="http://status.ocf.berkeley.edu">our status blog</a>.</p>
```
